import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import './Terms.css';

function Terms() {
    const [agreed, setAgreed] = useState(false);
    const navigate = useNavigate();

    const handleAgree = () => {
        localStorage.setItem('termsAccepted', 'true');
        navigate('/register');
    };

    const handleDecline = () => {
        localStorage.removeItem('termsAccepted');
        navigate('/register');
    };

    return (
    <div className="terms-page">
        <div className="terms-container">
            <Link to="/register" className="terms-back">← Back to Sign Up</Link>

            <h1>Terms &amp; Conditions</h1>
            <p className="terms-updated">Last updated: September 2026</p>
            
            <section>
                <h2>1. About Gigi</h2>
                <p>
                    Gigi is an AI-powered code assistant built to help with debugging,
                    explaining, and generating code for software and web development.
                    It was built as a student capstone project and is provided as-is,
                    for learning and demonstration purposes.
                </p>
            </section>
            
            <section>
                <h2>2. Your Account</h2>
                <p>
                    To use Gigi, you'll need to create an account with a name, email,
                    and password. You're responsible for keeping your login details
                    secure. Don't share your password or let others access your
                    account.
                </p>
            </section>
            
            <section>
                <h2>3. Acceptable Use</h2>
                <p>
                    Gigi is meant to help with legitimate coding and development
                    tasks. Please don't use it to generate harmful, malicious, or
                    illegal code, or to attempt to abuse, overload, or reverse-engineer
                    the service.
                </p>
            </section>

            <section>
                <h2>4. AI-Generated Content</h2>
                <p>
                    Gigi's responses are generated by an AI model and may occasionally
                    be inaccurate or incomplete, especially with newer libraries,
                    frameworks, or edge cases. Always review and test any code before
                    using it in a real project — Gigi is a helpful assistant, not a
                    replacement for your own judgment.
                </p>
            </section>

            <section>
                <h2>5. Your Data</h2>
                <p>
                    Your conversations are stored securely so you can pick up where
                    you left off. Passwords are encrypted and never stored in plain
                    text. As this is a student project, please avoid sharing sensitive
                    personal or confidential information in your chats.
                </p>
            </section>

            <section>
                <h2>6. Changes</h2>
                <p>
                    These terms may be updated as the project evolves. Continued use
                    of Gigi after changes means you accept the updated terms.
                </p>
            </section>

            <section>
                <h2>7. Contact</h2>
                <p>
                    Questions about these terms? Reach out at{' '}
                    <a href="mailto:ivieagho29@gmail.com">ivieagho29@gmail.com</a>.
                </p>
            </section>

            <div className="terms-agree-box">
                <label className="terms-checkbox">
                    <input 
                    type="checkbox"
                    checked={agreed}
                    onChange={(e) => setAgreed(e.target.checked)}
                    />
                    <span>I have read and agree to the Terms &amp; Conditions</span>
                </label>

                <div className="terms-actions">
                    <button className="terms-decline" onClick={handleDecline}>
                        Decline
                    </button>
                    <button
                    className="terms-accept"
                    onClick={handleAgree}
                    disabled={!agreed}
                    >
                        Accept &amp; Continue
                    </button>
                </div>
            </div>
        </div>
    </div>
    );
}

export default Terms;